name: CI Test Automation Pipeline

on:
  push:
    branches: [ develop, master ]
  pull_request:
    branches: [ develop, master ]

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    services:
      selenium:
        image: selenium/standalone-chrome:latest
        options: >-
          --name selenium
          --network-alias selenium

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Wait for Selenium to be ready
      run: |
        until curl -s http://localhost:4444/wd/hub/status | grep -q '"ready":true'; do
          echo "Waiting for Selenium..."
          sleep 5
        done

    - name: Run Behave tests
      run: |
        behave
      env:
        DISPLAY: :99.0
