name: CI Test Automation Pipeline

on:
  push:
    branches: [ develop, master ]
  pull_request:
    branches: [ develop, master ]

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    services:
      selenium:
        image: selenium/standalone-chrome:latest
        options: >-
          --name selenium
          --network-alias selenium

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Wait for Selenium to be ready
      run: |
        max_attempts=20
        wait_seconds=10
        attempt=0

        echo "Waiting for Selenium to be ready..."

        until [ $attempt -ge $max_attempts ]
        do
            if curl -s http://localhost:4444/wd/hub/status | grep -q '"ready":true'; then
                echo "Selenium is ready!"
                break
            fi

            echo "Selenium is not yet ready. Waiting..."
            attempt=$((attempt+1))
            sleep $wait_seconds
        done

        if [ $attempt -ge $max_attempts ]; then
            echo "Timeout: Selenium did not become ready after waiting for $((max_attempts * wait_seconds)) seconds."
            exit 1
        fi

    - name: Run Behave tests
      run: |
        behave
      env:
        DISPLAY: :99.0
